### ISSUE TITLE
Limitations des informations publiées et randomisation de l'ID member

### ISSUE THREAD

**Issue by jeey** [PartiPirate/personae#4]
Actuellement, il est assez facile de récupérer tout un tas d'information sur personnae. Les pseudos et les responsabilités me paraissent être assez légitimement diffusées publiquement. Par contre, les compétences devraient être invisibles publiquement.
Demande : rendre invisible au public les compétences

**Comment by farlistener** [comment]
Le point est fait, le 2 est à mettre dans une autre issue
