### ISSUE TITLE
Prévoir une limite aux nombres de procurations délégables à un membre

### ISSUE THREAD

**Issue by Relf-Oc** [PartiPirate/personae#8]
Il me semble qu'actuellement, un membre peut recevoir autant de délégations qu'il veut sans limite. Il faudrait être en mesure de pouvoir paramétrer les groupes dans Personae pour dire, par exemple : 
"Dans le cadre de l'AG, un membre ne peut recevoir que 3 délégations. Dans le cadre de la coordination nationale, un membre ne peut recevoir qu'un nombre de délégations égal à la racine carré des membres à jour de cotisation. Dans le cadre de la SI Stratcom, il n'y a pas de limite aux nombres de délégations que peut recevoir un membre."
Avec les messages d'erreurs correspondants, à la fois pour celui qui donne et pour celui qui reçoit la délégation et en particulier dans le cadre de délégations en cascade.

#PasTaper

**Comment by farlistener** [comment]
#TaperaiPas

**Comment by farlistener** [comment]
En passant, sera aussi rajouter la notion de dilution

**Comment by Relf-Oc** [comment]
c'est à dire?

**Comment by farlistener** [comment]
Un coefficient réducteur est appliqué entre chaque étage de délégation.

A, B, C ont chacun 1 point
Dilution à 90%

A donne à B : B a 1.9 points
B donne à C : C a 2.71 points

**Comment by Relf-Oc** [comment]
Ah mais en fait, c'est pas de la démocratie liquide, c'est de la démocratie homéopathique.
