### ISSUE TITLE
Prévoir une durée limitée dans le temps aux délégations

### ISSUE THREAD

**Issue by Relf-Oc** [PartiPirate/personae#9]
Il faudrait pouvoir donner à chaque membre la possibilité de dire "je donne délégation à tel autre membre pour une durée de X jours et je ne m'en occupe plus." Il faudrait faire en sorte que le membre qui donne la délégation soit malgré tout obligé de la confirmer (ou modifier) une fois tous les X mois (3 ? 6 ? 12 ?).
Si possible appliquer des durées différentes à chaque groupe, genre "je donne ma délégation pour l'AG continue pendant 6 mois, mais seulement pendant mes 2 semaines de vacances sur le groupe de travail sur la Justice."

#PasTaper

**Comment by Relf-Oc** [comment]
J'y pense en revoyant le titre de cette issue : 
que se passe-t-il si un adhérent qui a reçu des délégations devient "non-adherent" ? Est-ce que les délégations sautent automatiquement et sont rendus au mandataire ?

**Comment by farlistener** [comment]
Quand une fixation est refaite, oui

**Comment by farlistener** [comment]
#18 Sera intégré dans le moteur conditionnel

**Comment by farlistener** [comment]
Implémenté dans le moteur conditionnel
